### ISSUE TITLE
10.14.5外放没声音

### ISSUE THREAD

**Issue by MikuSugar** [Arecall/-Mac-os#1]
暗影精灵2（i5 6300hq gtx960m）在10.14.5 外放没有声音，耳机正常。

**Comment by Arecall** [comment]
点击声音图标，切换声音源，选择外放即可。

**Comment by DirectionLynn** [comment]
> 点击声音图标，切换声音源，选择外放即可。
点击声音图标没有 切换声音源的选项阿，音量能调节就是没声音

**Comment by u-mie** [comment]
> 点击声音图标，切换声音源，选择外放即可。

确实没声音？？怎么回事使用内置扬声器

**Comment by DirectionLynn** [comment]
id 改13 能用了就是声音有点小。

**Comment by MikuSugar** [comment]
换白苹果了，不折腾了
